In [31]:
#Support vector regression
#Need feature scaling for SVR
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [32]:
#Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [33]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [34]:
#For feature scaling we need to reshape the y
y = y.reshape(len(y),1)

In [35]:
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [36]:
#We need to split the data into training and testing set before featue scaling
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 0)

In [37]:
#Feature Scaling
#We need to do the feature scaling on Xtrain and ytrain
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [38]:
print(y_train)

[[ 1.15]
 [ 0.8 ]
 [-1.31]
 ...
 [ 0.28]
 [ 0.49]
 [-1.54]]


In [39]:
#Training the SVR model on the training set
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')#real basis function
regressor.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [40]:
# #Predicting the test results, have transform
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))



[[432.98 431.23]
 [460.91 460.01]
 [468.67 461.14]
 ...
 [468.91 473.26]
 [442.3  438.  ]
 [464.64 463.28]]


In [42]:
#Evaluating thr model performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8494246102002504